### ISSUE TITLE
P2812HNUF1 device dont boot from nand

### ISSUE THREAD

**Issue by feckert** [ScApi/P2812HNUFx-Pre-Build#2]
Hello
I have a problem in flashing openwrt on a P2812HNUF1 device
I made everything as descript in the wiki of openwrt for this device.

Short R17 and uploading of openwrt-lantiq-p2812hnufx_ram-u-boot.asc
-> Asc u-boot starts
( Commands with the associated output from uboot)
P-2812HNU-Fx # setenv ipaddr 10.1.3.62
P-2812HNU-Fx # setenv serverip 10.1.3.41
P-2812HNU-Fx # ping 10.1.3.41
ltq_phy: addr 0, link 1, speed 100, duplex 1
ltq_phy: addr 1, link 0, speed 10, duplex 0
ltq_phy: addr 17, link 0, speed 10, duplex 0
ltq_phy: addr 19, link 0, speed 10, duplex 0
ltq_phy: addr 5, link 0, speed 10, duplex 0
Using ltq-eth device
host 10.1.3.41 is alive
P-2812HNU-Fx # nand erase.chip
NAND erase.chip: device 0 whole chip
Skipping bad block at  0x01440000
Skipping bad block at  0x038c0000
Skipping bad block at  0x04d00000
Erasing at 0x7fe0000 -- 100% complete.
OK
P-2812HNU-Fx # tftp 0x80700000 openwrt-lantiq-p2812hnufx_nandtpl-u-boot.img
ltq_phy: addr 0, link 1, speed 100, duplex 1
ltq_phy: addr 1, link 0, speed 10, duplex 0
ltq_phy: addr 17, link 0, speed 10, duplex 0
ltq_phy: addr 19, link 0, speed 10, duplex 0
ltq_phy: addr 5, link 0, speed 10, duplex 0
Using ltq-eth device
TFTP from server 10.1.3.41; our IP address is 10.1.3.62
Filename 'openwrt-lantiq-p2812hnufx_nandtpl-u-boot.img'.
Load address: 0x80700000
Loading: ###
done
Bytes transferred = 32157 (7d9d hex)
P-2812HNU-Fx # nand write 0x80700000 0x0 0x7d9d
NAND write: device 0 offset 0x0, size 0x7d9d
 32157 bytes written: OK
P-2812HNU-Fx # 

Now i make a reset without shorting R17 but the device doesnot boot from nand?
What do i make wrong?
# Output after reboot

ROM VER: 1.0.5
CFG 06
NAND
NAND Read OK

Kind Regards Flo

**Comment by ScApi** [comment]
To erase all nand and get rid of Bad Blocks try "nand scrub", then try write u-boot with "nand write.e" command, also try download U-boot again.

**Comment by feckert** [comment]
Tank you for your reply i will try it tomorrow

**Comment by feckert** [comment]
Hello 

I have tested it and it works.
Now i Have a problem that the dsl is not working.
In the webgui i see

Status: DOWN
Line State: silent [0x200]

I have an other dsl modem and this one is in sync with the dislam?
Do I need an other firmware and what config do i need?

config vdsl 'dsl'
        option annex 'b'
        option firmware '/lib/firmware/vdsl.bin'
        option tone 'av'
        option xfer_mode 'ptm'

**Comment by ScApi** [comment]
Depends what is Your service provider.
12 cze 2015 11:27 "Florian Eckert" notifications@github.com napisał(a):

**Comment by feckert** [comment]
I am from Germany and my provider is "Telekom" i have dsl_lite

**Comment by ScApi** [comment]
Then You need to switch to Annex B firmware (it is in F3 folder)

**Comment by feckert** [comment]
In our office we have an dislam with annexA and annexB. I have loaded the difference firmware when i am in annexA or in annexB connection wit the dislam.
In annexA i get into state showtime_sync
In annexB i get into state handshake and the statemashine of the dsl firmware will be reseted and restarted.

UCI network config annexB
config vdsl
    annex b
    firmware /lib/firmware/vdsl.bin
    tone bv
    xfer_mode ptm

UCI network config annexA
config vdsl
    annex a
    firmware /lib/firmware/vdsl.bin
    tone av
    xfer_mode ptm

**Comment by ScApi** [comment]
Try newest images with updated vdsl/adsl firmware and driver.
