### ISSUE TITLE
Prebuild packages not in sync with kernel

### ISSUE THREAD

**Issue by janholtz** [ScApi/P2812HNUFx-Pre-Build#3]
Hi
I am getting this:

opkg install sqm-scripts
Installing sqm-scripts (1.0.3-1) to root...
Downloading http://scapi.zgora.pl/openwrt/46993/packages/packages/sqm-scripts_1.0.3-1_all.ipk.
Collected errors:
- satisfy_dependencies_for: Cannot satisfy the following dependencies for sqm-scripts:
-  kernel (= 3.18.21-1-049e9c79b7cf8fcdd356b59bc1084716) \*     kernel (= 3.18.21-1-049e9c79b7cf8fcdd356b59bc1084716) \*     kernel (= 3.18.21-1-049e9c79b7cf8fcdd356b59bc1084716) \*     kernel (= 3.18.21-1-049e9c79b7cf8fcdd356b59bc1084716) \*     kernel (= 3.18.21-1-049e9c79b7cf8fcdd356b59bc1084716) \* 
- opkg_install_cmd: Cannot install package sqm-scripts.

Any ideas?

**Comment by ScApi** [comment]
F1 or F3 image ?

**Comment by janholtz** [comment]
F1 Image

**Comment by janholtz** [comment]
All kmods, same result:

Installing kmod-ipt-iprange (3.18.21-1) to root...
Downloading http://scapi.zgora.pl/openwrt/46993/packages/base/kmod-ipt-iprange_3.18.21-1_lantiq.ipk.
Configuring kmod-ipt-conntrack-extra.

Collected errors:
- satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-ipt-iprange:
-  kernel (= 3.18.21-1-049e9c79b7cf8fcdd356b59bc1084716) \* 
- opkg_install_cmd: Cannot install package kmod-ipt-iprange.
- pkg_run_script: package "kmod-ipt-conntrack-extra" postinst script returned status 255.
- opkg_configure: kmod-ipt-conntrack-extra.postinst returned 255.

**Comment by ScApi** [comment]
Will check asap, sorry but my F1 is dead so I cannot test it fully, probably something went wrong during compilation.

**Comment by janholtz** [comment]
Cool, thanks a ton!

**Comment by janholtz** [comment]
If you send me detailed instructions, I'll be happy to compile & test (and even host) the results...

**Comment by ScApi** [comment]
Please flash updated image and test new rev.

Best Regards
Sylwester
24 wrz 2015 9:43 AM "janholtz" notifications@github.com napisał(a):

**Comment by janholtz** [comment]
Sysupgrade, yes?

**Comment by ScApi** [comment]
Yes.

Best Regards
Sylwester

**Comment by janholtz** [comment]
Sorry to be such a n00b, upload of sysupgrade.tar not working, is there something obvious I'm not doing?

**Comment by ScApi** [comment]
Flash *sysupgrade.tar as normal image via luci.

Best Regards
Sylwester
24 wrz 2015 11:17 AM "janholtz" notifications@github.com napisał(a):

**Comment by janholtz** [comment]
nope, I'll do a re-install from scratch...

**Comment by janholtz** [comment]
Nope, exact same problem:

Installing sqm-scripts (1.0.3-1) to root...
Downloading http://scapi.zgora.pl/openwrt/47026/packages/packages/sqm-scripts_1.0.3-1_all.ipk.

Collected errors:
- satisfy_dependencies_for: Cannot satisfy the following dependencies for sqm-scripts:
-  kernel (= 3.18.21-1-049e9c79b7cf8fcdd356b59bc1084716) \*     kernel (= 3.18.21-1-049e9c79b7cf8fcdd356b59bc1084716) \*     kernel (= 3.18.21-1-049e9c79b7cf8fcdd356b59bc1084716) \*     kernel (= 3.18.21-1-049e9c79b7cf8fcdd356b59bc1084716) \*     kernel (= 3.18.21-1-049e9c79b7cf8fcdd356b59bc1084716) \* 
- opkg_install_cmd: Cannot install package sqm-scripts.

**Comment by janholtz** [comment]
If  I build from the lastest trunk, can I compile my own?

**Comment by janholtz** [comment]
Does this apply:
Tweak the LINUX_VERSION variable in target/linux/ar71xx/Makefile.
?

**Comment by ScApi** [comment]
No, it's for ar71 not lantiq and affects kernel version only, send full bootlog to pastebin and give link to it.
As for openwrt git, yes You can compile but without eeprom for wifi and vdsl.

**Comment by janholtz** [comment]
With git, can I add your firmware images to /lib/firmware after the fact?

**Comment by ScApi** [comment]
Yes.

**Comment by janholtz** [comment]
Apologies, I reflashed your new release, and it works perfectly!
2 Thumbs up, excellent pre-build.
